[project]
name = "pytrale"
version = "0.1.0"
description = "Python package to analyze weights exported from trale"
authors = [
    {name = "braniii", email = "''"},
]
dependencies = [
    "matplotlib>=3.8.3",
    "prettypyplot>=0.10.1",
    "numpy>=1.26.4",
    "tqdm>=4.67.1",
]
requires-python = ">=3.11"
readme = "README.md"
license = {text = "MIT"}

[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"


[dependency-groups]
dev = [
    "jupyter>=1.1.1",
]
